### ISSUE TITLE
exec spawning makes the default wallpaper stop loading after first boot if exec spawning is used for systemui

### ISSUE THREAD

**Issue by thestinger** [AndroidHardeningArchive/bugtracker#397]

**Comment by thestinger** [comment]
Strangely, this doesn't seem to impact the Nexus 5X. It's odd for this to be device-specific.

**Comment by canary5** [comment]
I had same on 5x, but on maybe 3rd boot

**Comment by thestinger** [comment]
Maybe it's a race condition then.

**Comment by thestinger** [comment]
This appears to be fixed, so it shouldn't be a problem anymore with the next release.

**Comment by thestinger** [comment]
Still present in Oreo MR1.
