### ISSUE TITLE
Implement Duress Password Feature

### ISSUE THREAD

**Issue by rorymbyrne** [AndroidHardeningArchive/bugtracker#413]
Implement duress password unlock feature. Probably similar to Blackberry's feature (password backwards). Notification to selected contact or immediate delete.

**Comment by thestinger** [comment]
We'll accept an implementation of this for wiping the device when a passphrase is entered, but we don't want more complexity right now.

**Comment by thestinger** [comment]
Migrated to the new issue tracker: https://github.com/GrapheneOS/os_issue_tracker/issues/29.
