### ISSUE TITLE
content filtering support in Chromium

### ISSUE THREAD

**Issue by thestinger** [AndroidHardeningArchive/bugtracker#511]
Minimal implementation:

* UI indicating when content is blocked and offering the ability to toggle off filtering per-site (as part of site settings). This is blocked on #512 since it makes sense to reuse that user interface.
* Domain-based filtering blocking connections outright

Further steps:

* auto-updating filter subscriptions
* custom filter subscriptions
* extended EasyList syntax support (CSS selectors, element hiding, etc.) - this can be done gradually

**Comment by thestinger** [comment]
Blocked on #512 since it would be nice to reuse that user interface.

**Comment by thestinger** [comment]
Brave directly extends Chromium with these capabilities at least for Android, so that's an interesting place to look.

**Comment by thestinger** [comment]
(the first step is still really #512 though, this should all be as closely integrated as possible and based on the standard site settings feature)

**Comment by zuglufttier** [comment]
Maybe dns66 could become a nice addition to CopperheadOS or an altervative to browser based content filtering: https://github.com/julian-klode/dns66

**Comment by thestinger** [comment]
It needs to be able to show when content is being blocked and permit unblocking it. dns66 has silently broken OS updates before which is an example of what it can do, and then people struggle to figure out what is wrong and blame the software that's breaking or their network when it's a filtering app they installed.

**Comment by thestinger** [comment]
This is being implemented in upstream Chromium so we'll probably be able to build on that.

**Comment by thestinger** [comment]
Migrated to https://github.com/AndroidHardening/chromium_patches/issues/10.
