### ISSUE TITLE
add support for isolated shared storage

### ISSUE THREAD

**Issue by thestinger** [AndroidHardeningArchive/bugtracker#526]
In almost all cases, apps should be avoiding shared storage and using content providers and other sane mechanisms with fine-grained control for sharing data with other apps. However, the reality is that many apps including some in the base system abuse shared storage as the default and often only option for their data. It makes sense for it to be an option, but not the default. Apps should really own and control their own data, with it moved to shared storage only upon request by the user.

This can be worked around by adding isolated shared storage, where apps are really directed towards a subdirectory within shared storage that's only accessible by the assigned app and the built-in file manager. The directory can be named based on the app id and a hash of the public key it's signed with, with it only accessible to that app id + signature along with an exception for the built-in file manager. Users will be able to manage and share the files via the file manager, just as they could before, but otherwise the data will be private and not automatically scanned by the media scanner, etc.

Optionally, if more convenience is desired at the expense of security (shouldn't necessarily be implemented): Isolated shared storage can be a per-app toggle with it set as the default for legacy apps. For modern apps, it could potentially be offered as an option in the prompts for requesting access to shared storage. After the user selects allow in the storage access permission prompt, it could be followed up with one asking whether it should be isolated.

**Comment by bunsim** [comment]
This is also important if you have to run untrustworthy applications that don't have suspicious permissions other than shared storage. On stock Android shady Chinese chat apps I have to use for work can see all my camera photos, downloads, etc, and it's difficult to use my phone under the assumption that shared storage is always compromised. Blocking app access to things like location and microphone typically is handled gracefully, but these apps store things like chat logs in shared storage and thus completely break without access.

**Comment by thestinger** [comment]
You can use multiple user profiles.

**Comment by bunsim** [comment]
That's a solution, but it would prevent me from getting notifications from the "spyware" app when using my "safe" user profile.

**Comment by thestinger** [comment]
This is no longer planned since it will be provided by Android Q. See https://gist.github.com/thestinger/e4bb344dcc545d2ee00dcc22fd886f29 for an overview of all the privacy features introduced in Q within the context of this project.
