### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by spacekitteh** [AndroidHardeningArchive/bugtracker#533]
Since Android (and therefore CopperheadOS) is such a huge project, continuous integration (with static and dynamic analysis, eventually) should be added. This is a pretty big task, but ultimately, one that will pay off.

### CI solutions
* Hydra
  * Based on [Nix](https://nixos.org), so it takes every build input into account (e.g. version of gcc you're compiling with, version of a particular library, etc) automatically.
  * Very easy to break up a huge build into individual components with individual options and individual tests and have everything "just work"
  * Requires writing a Nix expression to evaluate, which is more difficult initially but pays off huge
* Travis CI
  * Hard to jury-rig into doing dependent builds
    * [Solution as a Gradle plugin](https://github.com/adrianbk/gradle-travisci-trigger-plugin)
  * 50 minute job timeout (arbitrary multiple jobs per build, though)
* [Linaro Developer Cloud](https://www.linaro.cloud/) seems to be a new hardware test cloud for ARMv8 stuff
  * [Outdated overview](https://wiki.linaro.org/Platform/Android/LinaroAndroidBuildService)
* Jekins probably has the best support overall for AOSP right now.
  * [Repo plugin for Jenkins](https://wiki.jenkins-ci.org/display/JENKINS/Repo+Plugin)
  * [Swarm slave for AOSP](https://wiki.jenkins-ci.org/display/JENKINS/Swarm+Plugin) used with this [Docker container AOSP build script](https://hub.docker.com/r/praqma/aosp-build-container/)
  

### Analysis tools
* Valgrind
* Lint
* Kcov
* Kasan
* Android [Compatibility Test Suite](https://source.android.com/compatibility/cts/index.html)

### Related work
* [ibuild](https://github.com/daviding924/ibuild) 
  >ibuild is a toolkit for AOSP setup, build, continuous integration, release and engineering computing node by bash script and other Open Source tools. It is simpleness, lightweight, decoupling, modularization, parameterization, C/S and P2P mixed architecture.

* [How-to Automate Your ROM Build Process Using Jenkins - Setup Nightlies](http://forum.xda-developers.com/showthread.php?t=2467004)

**Comment by kewde** [comment]
I would like to propose looking into [coverity](https://scan.coverity.com/), it has been very very helpful and gives the most detailed analysis I've ever seen in a tool.

HTC has used this tool before and found quite the amount of high-level defects.

[Coverity sample on Android kernel](https://www.coverity.com/library/pdf/a-look-inside-the-android-kernel.pdf)

**Comment by Rudd-O** [comment]
Not what you want, but I hope it's useful: https://github.com/Rudd-O/copperheados-build

**Comment by thestinger** [comment]
Closing as a legacy issue. It can be revisited for GrapheneOS.
