### ISSUE TITLE
Provide option to disable Internet connectivity checking

### ISSUE THREAD

**Issue by nullchinchilla** [AndroidHardeningArchive/bugtracker#572]
Currently CopperheadOS contacts Google to confirm Internet connection and there's no way to turn off this behavior. I understand that this is probably the best way to confirm Internet connection, since Google is basically always available.

However, Google is blocked in China, and there may be other environments where Internet connection is only available over a proxy. Android would then put up an annoying warning sign, and it often refuses to automatically connect, which in practice means that the phone would disconnect if left unattended. This is becoming extremely irritating when using the OS while traveling in China, in particular when the mobile radio is turned off and only WiFi is used, and China is probably one of the places particularly suitable for doing exactly that.

Would it be possible to disable the entire Internet-checking code by means of a setting? It seems like Android [already has a setting for this](https://android.stackexchange.com/questions/100657/how-to-disable-captive-portal-detection-how-to-remove-exclamation-mark-on-wi-fi), but changing that setting requires root permissions. Android phones sold in China typically are configured to ping a Chinese site (usually the website of the OEM) instead, though that is obviously unacceptable for CopperheadOS.

**Comment by thestinger** [comment]
This can be done via adb already, it doesn't require root, it just isn't exposed via the UI.

**Comment by thestinger** [comment]
I'm likely going to host my own version of this service for GrapheneOS.
