### ISSUE TITLE
specs for Suzy-Q debug cable for Pixel 2 and Pixel 2 XL

### ISSUE THREAD

**Issue by thestinger** [AndroidHardeningArchive/bugtracker#788]

**Comment by xbtc-im** [comment]
suzy-q ? really ? this sounds like a porn star ... :)

**Comment by thestinger** [comment]
cc @ScottyBauer 

Can you send us this?

**Comment by ScottyBauer** [comment]
@thestinger Yeah, want me to message dnj or I can send you how I wired it up on IRC tomorrow?

**Comment by npjohnson** [comment]
@scottyBauer

Hey, could you also shoot me the wiring method?

If you could shoot me an email, I'd really appreciate it, need UART on Taimen for mainline work.

**Comment by thestinger** [comment]
Migrated to https://github.com/AndroidHardening/os_issue_tracker/issues/4.
