### ISSUE TITLE
link not valid

### ISSUE THREAD

**Issue by ort163** [AndroidHardeningArchive/bugtracker#809]
On the main page https://copperhead.co/android/docs/technical_overview
You have a link to  **the issues tagged as enhancements on the tracker.**  This goes to no results matched in github.
i.e. change  label:enhancement  to   label:"Type: enhancement"

**Comment by thestinger** [comment]
This is obsolete since there will need to be entirely new documentation for the new hardened OS (https://github.com/AndroidHardening).
