### ISSUE TITLE
CarrierConfig vendor.xml for Pixel 2 (XL)

### ISSUE THREAD

**Issue by thestinger** [AndroidHardeningArchive/bugtracker#826]

**Comment by thestinger** [comment]
It seems they might have stopped using this and moved to the protobuf files, without code in AOSP to handle them.

**Comment by xbtc-im** [comment]
What's this with the CarrierConfig anyway ? Wasn't the SIM card supposed to handle all that ?

**Comment by thestinger** [comment]
Well, it doesn't, there's a massive database of default APNs and the right one is picked based on ids from the SIM card. If there isn't an entry, you need to manually enter an APN for working SMS/MMS and data. This CarrierConfig stuff is needed for some things outside the scope of APN configuration.

**Comment by xbtc-im** [comment]
Yes, but besides the APN-s there are other issues ? For me there is no issue manually editing the APN settings for the internet, those can easily be looked up anyway ... And does anyone still use MMS ? :)

**Comment by thestinger** [comment]
Yes, there are other issues, but it mostly works fine with just the standard APN database otherwise we wouldn't have launched Pixel 2 (XL) support. We only do this on the Pixel and Pixel XL, never did it on the Nexus 5X and 6P.

**Comment by thestinger** [comment]
https://github.com/CopperheadOS/device_google_marlin/blob/oreo-m2-release/overlay/packages/apps/CarrierConfig/res/xml/vendor.xml

**Comment by xbtc-im** [comment]
Off topic, i wonder what the software in the radio partition is capable of ... AFAIK that's a RTOS handling all the network/radio stuff, i wonder how much access does it have to the main memory / cpu.

**Comment by thestinger** [comment]
Components like the cellular radio, GPU, media decode/encode engine, etc. are contained by IOMMUs.

**Comment by thestinger** [comment]
PCIe peripherals may or may not be contained well. You would need to do research more specific to devices. Most components are part of the SoC and the IOMMU configuration is reused across all the devices using the SoC unless they do something very strange.

There's a higher chance of a component separate from the SoC not being properly isolated. A component being on the SoC or having access to memory doesn't mean it isn't contained and likewise a component not being on the SoC doesn't mean it is contained.

**Comment by xbtc-im** [comment]
Thanks for the clarification
