### ISSUE TITLE
4G option missing in Preferred Network Type on Pixel 2 XL

### ISSUE THREAD

**Issue by xbtc-im** [AndroidHardeningArchive/bugtracker#840]
Not sure it's a valid issue but another user reported this too on reddit ... 
![screenshot_20180307-094245](https://user-images.githubusercontent.com/32508652/37082101-7ba077e6-21e3-11e8-88ab-8da36b337118.png)

**Comment by ScottyBauer** [comment]
I think this is an upstream bug too. But if you turn your phone sideways (long way) more options pop up.

**Comment by xbtc-im** [comment]
Hm, you are right, i never thought of that. Interesting "workaround" :)

**Comment by thestinger** [comment]
It might be a Pixel 2 XL layout bug. I don't know.

**Comment by thestinger** [comment]
Like the issue that happens with the keyboard... ?

**Comment by xbtc-im** [comment]
It might be related, however the nav buttons in the keyboard settings do not go away when changing layout ...

**Comment by pintopwnie** [comment]
Confirmed issue with Pixel 2 as well. Selecting 4G when having the phone sideways does not save it and resolves to 2G instead once you put it vertical again.

**Comment by xbtc-im** [comment]
You can type `*#*#4636#*#*` into the Dialer app, go to Phone Information and select the band from there. Default should be LTE/UMTS auto (PRL), depending on your carrier of course, but you can select different network types from there.

**Comment by thestinger** [comment]
I don't know if this was fixed upstream but it will need to be investigated again with Android Pie and filed as an issue on the new bug tracker if it's still a problem.
