### ISSUE TITLE
Pixel Visual Core infrastructure has memory corruption issues uncovered by the hardened malloc

### ISSUE THREAD

**Issue by thestinger** [AndroidHardeningArchive/bugtracker#842]

**Comment by thestinger** [comment]
cc @ScottyBauer

**Comment by ScottyBauer** [comment]
I've reported this to qcom, It's in their code and I don't have sources to it.

**Comment by ScottyBauer** [comment]
I asked for sources (unlikely I'll get it). But in the case I do i'll get them a patch

**Comment by thestinger** [comment]
The camera stack including Easel still appears to be problematic with Android Pie, but there can be new issues filed about all these things.
